# Generated by Django 3.0 on 2019-12-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='time_available',
        ),
        migrations.AddField(
            model_name='listing',
            name='end_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='listing',
            name='start_date',
            field=models.DateField(default='2000-12-12'),
        ),
    ]
