# Generated by Django 3.0 on 2019-12-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20191212_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateField(default='2000-12-12'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateField(default='2000-1-1'),
        ),
    ]
