# Generated by Django 3.0 on 2019-12-12 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20191212_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
